### ISSUE TITLE
Will fail to build with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by hosiet** [mytbk/fqterm#7]
This software will fail to build from source when using OpenSSL 1.1.0. Please investigate into it.

Please refer to https://wiki.openssl.org/index.php/1.1_API_Changes for potential API breakages.

**Comment by mytbk** [comment]
I can build with OpenSSL 1.1.0b installed at /usr/local/openssl and `cmake -DOPENSSL_ROOT_DIR=/usr/local/openssl`. What is the error in your build?

**Comment by hosiet** [comment]
```
cd /build/fqterm/obj-x86_64-linux-gnu/src/protocol && /usr/bin/g++   -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_XML_LIB -isystem /usr/include/qt4 -isystem /usr/include/qt4/QtScript -isystem /usr/include/qt4/QtGui -isystem /usr/include/qt4/QtXml -isystem /usr/include/qt4/QtNetwork -isystem /usr/include/qt4/QtCore -I/build/fqterm/src/protocol/internal -I/build/fqterm/src/protocol/../common -I/build/fqterm/obj-x86_64-linux-gnu/src/protocol  -g -O2 -fdebug-prefix-map=/build/fqterm=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -D FQTERM_VERSION_STRING=\"0.9.8\" -o CMakeFiles/fqterm_protocol.dir/internal/fqterm_ssh_buffer.cpp.o -c /build/fqterm/src/protocol/internal/fqterm_ssh_buffer.cpp
In file included from /build/fqterm/src/protocol/internal/fqterm_ssh_buffer.cpp:25:0:
/build/fqterm/src/protocol/internal/fqterm_ssh_buffer.cpp: In member function 'void FQTerm::FQTermSSHBuffer::putSSH2BN(BIGNUM*)':
/build/fqterm/src/protocol/internal/fqterm_ssh_buffer.cpp:135:20: error: invalid use of incomplete type 'BIGNUM {aka struct bignum_st}'
   FQ_VERIFY(!bignum->neg);  // currently we don't support negative big number.
                    ^
/build/fqterm/src/protocol/../common/fqterm_trace.h:280:10: note: in definition of macro 'FQ_VERIFY'
     if(!(expr)) {                                   \
          ^~~~
In file included from /usr/include/openssl/bn.h:32:0,
                 from /build/fqterm/src/protocol/internal/fqterm_ssh_buffer.h:24,
                 from /build/fqterm/src/protocol/internal/fqterm_ssh_buffer.cpp:26:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'BIGNUM {aka struct bignum_st}'
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
src/protocol/CMakeFiles/fqterm_protocol.dir/build.make:209: recipe for target 'src/protocol/CMakeFiles/fqterm_protocol.dir/internal/fqterm_ssh_buffer.cpp.o' failed
make[3]: *** [src/protocol/CMakeFiles/fqterm_protocol.dir/internal/fqterm_ssh_buffer.cpp.o] Error 1
make[3]: Leaving directory '/build/fqterm/obj-x86_64-linux-gnu'
CMakeFiles/Makefile2:323: recipe for target 'src/protocol/CMakeFiles/fqterm_protocol.dir/all' failed
make[2]: *** [src/protocol/CMakeFiles/fqterm_protocol.dir/all] Error 2
make[2]: Leaving directory '/build/fqterm/obj-x86_64-linux-gnu'
Makefile:152: recipe for target 'all' failed
make[1]: *** [all] Error 2
```

**Comment by mytbk** [comment]
I see. I was using the headers of OpenSSL 1.0.2 at /usr/include instead of /usr/local/openssl. I can confirm this when I add `-isystem /usr/local/openssl/include` to compile this file.

**Comment by mytbk** [comment]
I've pushed one commit at openssl-1.1 branch, I don't know if this is enough.

**Comment by mytbk** [comment]
There are more things broken in the new OpenSSL, I'll try to fix it later. Before that, I think the FQTerm native SSH support should be disabled. Actually, I recommend using openssh (in quick connect dialog, select protocal as 'local') over FQTerm SSH.

**Comment by hosiet** [comment]
Debian has decided to [ship with OpenSSL 1.1.0 by default](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827061). To ensure that fqterm can be shipped with next Debian release (Debian 9, "Stretch"), this bug should be fixed before 2016-12-25.

It would be great if you could fix it before 2017 comes. Either a patch or a new release would all be highly appreciated.

**Comment by mytbk** [comment]
@hosiet Please test the openssl-1.1.0-rebased branch, I have tested it on OpenSSL 1.0.2 and 1.1.0.

**Comment by hosiet** [comment]
I can confirm that the openssl-1.1.0-rebased branch can be compiled against both openssl1.0.2 and openssl1.1.0. Good job!

**Comment by mytbk** [comment]
Merged to master branch.
